### ISSUE TITLE
Add scripts for QEMU

### ISSUE THREAD

**Issue by n0toose** [pyavitz/rpi-img-builder#1]
Giving the ability to easily compile an image and then test it out on QEMU could help people do things such as
* be drawn into development, regardless of whether or not they have a Raspberry Pi laying around
* make testing much more convenient under specific circumstances
* show some well-deserved respect to our beloved SD cards
* allow for CI tests in the future (mayhaps)

**Comment by pyavitz** [comment]
Alright. I'll look into this.
