### ISSUE TITLE
Build Images with desktop?

### ISSUE THREAD

**Issue by rcla** [pyavitz/rpi-img-builder#13]
Thank you for your great work done.

In testing, every time I want to install a desktop it takes a long time.

What are the steps to build an image that includes a desktop?

Could there be a "Downloadable Image" that includes a desktop?

**Comment by pyavitz** [comment]
You would need to edit `lib/source.txt` and change the img size to reflect the packages ur installing.

```
# stage1
RPI4="2575MB"
RPI3="2575MB"
RPI0="2250MB"
```

Where I would add the name of the meta-package.

```
PKGS2="cpu hwinfo neofetch haveged resolvconf git build-essential net-tools \
        ifplugd fuse wpasupplicant wireless-tools usbutils alsa-utils gettext \
        bison flex mc nano figlet toilet curl dialog python3 python3-setuptools \
        openssh-client openssh-server ntfs-3g bc zram-tools libncursesw5-dev \
        libssl-dev autopoint autoconf automake pkg-config libtool fake-hwclock \
	python python-setuptools"
```

As for creating a downloadable Desktop Image; which one would you like?

**Comment by rcla** [comment]
Thanks for your guide, I will try this week.

In the debian image I would like full mate desktop.

**Comment by pyavitz** [comment]
I placed a Mate test image in the [release](https://github.com/pyavitz/rpi-img-builder/releases/tag/5.4.44) section along with a screenshot.

Since you aren't the first person to ask, I'll create a Raspberry Pi 4B Desktop branch.
If you should find any major bugs or annoyances please report back.

**Comment by rcla** [comment]
Great news!

This weekend, I will be testing your Mate image.

**Comment by rcla** [comment]
With Mate test image, although physically I have the Internet working through LAN and browsing with chromium ok.
I wanted to configure the wifi with a GUI, so I installed: 'network-manager-gnome'

However, wired and wireless networks appear 'device not managed'.

Attached screenshot:
![Screenshot at 2020-06-05 18-40-19](https://user-images.githubusercontent.com/45245617/83928747-6b73d200-a756-11ea-8d87-7a9af74e7cb0.png)

**Comment by pyavitz** [comment]
That's because it is currently still using ifupdown. In the next test img I'll add network manager.

```
sudo apt install network-manager network-manager-gnome -y
```
msg during install:
```
The following network interfaces were found in /etc/network/interfaces
which means they are currently configured by ifupdown:
- eth0
- wlan0
If you want to manage those interfaces with NetworkManager instead
remove their configuration from /etc/network/interfaces.
```
It means you need to edit /etc/network/interfaces

Just leave the following:
```
### Interfaces
source /etc/network/interfaces.d/*
```
This has been tested using a new Xfce4 test img I'm working on.
![image](https://raw.githubusercontent.com/pyavitz/misc/master/Screenshot_2020-06-05_20-22-42.png)

**Comment by rcla** [comment]
Thank you.

Now it works!.

Sound via HDMI, I fixed it, uncomment the following line inside the file config.txt.
`hdmi_drive=2`

Also that screenshot of your xfce4, looks great.
