### ISSUE TITLE
Xfce4 Destop Image freeze after inactivity

### ISSUE THREAD

**Issue by rcla** [pyavitz/rpi-img-builder#14]
With test image 'rpi-4-b-xfce4-debian-buster-2020-06-06-v8.7z',
after a period of inactivity, it does not respond, it freezes.

I fixed it, installing the package 'xscreensaver' since in debian buster the package 'xfce4-screensaver' does not exist.

**Comment by pyavitz** [comment]
I did notice that if `Power Manager > Security: Automatically lock the session: When screensaver is activated` is set, it does freeze and not come back. I'll add xscreensaver to the package list and rebuild the test image.

Thanx for the input and for testing.

**Comment by pyavitz** [comment]
Bluetooth seems to be broken in the latest test builds. As soon as it gets resolved or I figure out what has changed, I'll upload some new images.

**Comment by pyavitz** [comment]
Alright. Bluetooth has been sorted and I added a new image for Xfce4. 
You can find it under [Release](https://github.com/pyavitz/rpi-img-builder/releases/tag/desktop).

**Comment by rcla** [comment]
Thanks for fixing it.

I tried the new version and it automatically applied the Numix theme, it looks very pretty.

In addition to running the audio in HDMI, without having to modify the file config.txt
