### ISSUE TITLE
Ubuntu image and Network Manager

### ISSUE THREAD

**Issue by rcla** [pyavitz/rpi-img-builder#15]
Testing the image 'rpi-4-b-ubuntu-20.04-2020-06-11-v8.7z',
I installed 'ubuntu-desktop', and have the 'Network manager' handle wireless networks,
modifying the following files:

/etc/network/interfaces:
```
### Interfaces
source /etc/network/interfaces.d/*
```

/etc/wpa_supplicant/wpa_supplicant.conf:
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

#network={
#	ssid="mywifissid"
#	scan_ssid=1
#	key_mgmt=WPA-PSK
#	psk="wifipasskey"
#}
```

However, after those changes, the wired network does not work.

**Comment by pyavitz** [comment]
I haven't loaded up the img, but I'm assuming you probably need to disable networking - `sudo systemctl disable networking`

**Comment by rcla** [comment]
> I haven't loaded up the img, but I'm assuming you probably need to disable networking - `sudo systemctl disable networking`

I tried, but it still doesn't work.

With ifconfig, eth0 does not appear.

**Comment by pyavitz** [comment]
I fixed the problem by removing the following:
`sudo rm -f /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf`

Followed by a reboot.

I placed a new image in [Release](https://github.com/pyavitz/rpi-img-builder/releases) that comes with Network Manager pre-installed and with the above file removed.

**Comment by rcla** [comment]
I removed the file you suggest and now it works!

Thank you so much.
