### ISSUE TITLE
Add quirks handler for usb boot code to handle certain usb device boot problems (some UAS devices).

### ISSUE THREAD

**Issue by arakeen** [pyavitz/rpi-img-builder#17]
Adding usb_storage.quirks=0bc2:231a:u to /boot/cmdline.txt. Switch the hex to the lsusb output of the address of the device being booted.

**Comment by pyavitz** [comment]
Here is a sticky on the forum concerning the matter - https://www.raspberrypi.org/forums/viewtopic.php?t=245931
I'm currently working on a write2usb script and once done with review, will be adding it to the builder. 
`usb_storage.quirks` will be added to a trouble shoot section in the README.md.
