### ISSUE TITLE
Provide option to compile kernels into .deb files

### ISSUE THREAD

**Issue by n0toose** [pyavitz/rpi-img-builder#3]

**Comment by n0toose** [comment]
I'd like to work on this, if that's not too big of a deal.

My approach would be the following;
* create new option in Makefile that enables an environment variable and then runs the `make-kernel` script.
* if the said environment variable has been toggled, run the following command on the root of the kernel sources; `fakeroot debian/rules binary`

I'd just like to get the green light on this, thanks!

**Comment by pyavitz** [comment]
Sounds good.

If ur going to be working directly from the hub, please use feature branch.

**Branches**:
master - default
feature
rpi4b - depreciated 
rpi3b - depreciated
rpi0w - depreciated

**Comment by n0toose** [comment]
> Sounds good.
> 
> If ur going to be working directly from the hub, please use feature branch.
> 

I'll open a pull request, so that you'll be able to tell apart tiny corrections and details before it gets merged, since I'm still a bit unfamiliar with the codebase.

**Comment by pyavitz** [comment]
**Mission accomplished!**

Feature branch is now ready for testing.

**update:**
``` 
Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/pi/rtl8812au/88XXau.mod.o
  LD [M]  /home/pi/rtl8812au/88XXau.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.32-v8'
```

x86 cross compiling seems to be a success. "the headers are usable"
I'm running into trouble cross compiling from other architectures, but this could just be my setup.
