### ISSUE TITLE
using clang/llvm with lto for kernel compiling

### ISSUE THREAD

**Issue by ptr1337** [pyavitz/rpi-img-builder#31]
Since Kernel 5.11 + lto can be used for compiling which could be a great performance improvement 
The compile time would be little bit longer. 

Also adding -mtune="x" for compile flags can improve the kernel

**Comment by ptr1337** [comment]
still not implemented ? :x 

i using it since 5.13 on my rig and there is definitly a performance increase. 
However, also to retarded to use the new irc :D

**Comment by pyavitz** [comment]
> still not implemented ? :x
> 
> i using it since 5.13 on my rig and there is definitly a performance increase.
> However, also to retarded to use the new irc :D

I just haven't gotten around to implementing it yet, as I've never personally used it and not 100% sure how to integrate it into the builder. I'll do some reading and asking around and see what I can do within the next week or so.

As for IRC, it's not rocket science or anything :)

**Comment by ptr1337** [comment]
the new one is rocket science. 

i can help you if you want

**Comment by pyavitz** [comment]
Well you know where to find me, if you wanna chat.

If you have a working example, you can also post it here or Projects, much like Tenkawa did with ccache.

**Comment by pyavitz** [comment]
Ideas, thoughts and or changes?

```sh
git clone -b clang https://github.com/pyavitz/rpi-img-builder.git clang
```

**Comment by ptr1337** [comment]
I try a  full compile. 

but mostly i would say changegs in the defconf for lto.

**Comment by ptr1337** [comment]
-fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -ffat-lto-objects -fuse-linker-plugin

maybe need thiis CC FLAAGS somehow

**Comment by pyavitz** [comment]
> I try a full compile.
> 
> but mostly i would say changegs in the defconf for lto.

Trying to  figure out how to remove this warning:
```sh
dpkg-architecture: warning: specified GNU system type aarch64-linux-gnu does not match CC system type
aarch64-unknown-linux-gnu, try setting a correct CC environment variable
```
Happens on both cross and native, just a diff warning. Although the kernels appear to be fine after the build?

**Comment by ptr1337** [comment]
BEcause Cross compiling.
Let me check, ill do native.

**Comment by ptr1337** [comment]
https://github.com/torvalds/linux/blob/v5.13/arch/arm64/Kconfig

**Comment by ptr1337** [comment]
Didnt found the LTO option in the config. 
its compiling now. ,  if i see lto compiling ill tell  you

**Comment by pyavitz** [comment]
I made further adjustments to it and added missing depends. Cross is kinda sketchy using Focal, but running Native using Hirsute seems to work just fine.

**Comment by ptr1337** [comment]
LLVM=1 LLVM_IAS=1
and IAS also please.

Also you need to adjust the defconfig for lto compiling.
