### ISSUE TITLE
After make rpi3-image failure, loop mounts stay mounted

### ISSUE THREAD

**Issue by ghpille** [pyavitz/rpi-img-builder#37]
A next run of "make rpi3-image" may fail because of that, when unmounting at the end.

**Comment by pyavitz** [comment]
If there is a fail during the run of creating the image ,the loop(s) will remain mounted. You will need to run `make cleanup` after a fail. I usually run it twice to play it safe. I've also noticed in some cases it won't use the same digits on a loop after that, this is especially noticeable when using docker.

What OS / Distro are you running to make the img?

https://github.com/pyavitz/rpi-img-builder#miscellaneous

**Comment by pyavitz** [comment]
I believe this was answered. If it wasn't feel free to reopen the issue.
