### ISSUE TITLE
make rpi3-image fails when nameserver 8.8.8.8 cannot be reached

### ISSUE THREAD

**Issue by ghpille** [pyavitz/rpi-img-builder#38]
I have my own nameserver, which is the only one that can be reached because of my firewall configuration.

I had to modify scripts/devuan-stage2 to use my nameserver in stead of 8.8.8.8 or 8.8.4.4.

**Comment by pyavitz** [comment]
Okay, I believe I misunderstood what you were saying before. I can modify the userdata.txt file so said part of stage2 is made a variable and can just be edited on the fly in such cases of this.

Does that sound acceptable?

**Comment by pyavitz** [comment]
Hopefully this resolves said issue for you: https://github.com/pyavitz/rpi-img-builder/commit/58a0c551aa607c4eadebac88ba715132bb7ee367

After creating said userdata.txt file, review the file and adjust the variables and functions as needed.

**Comment by pyavitz** [comment]
I believe this was resolved. If it wasn't feel free to reopen the issue.
