### ISSUE TITLE
Possibility for further changes to kernel menuconfig after rpi3-kernel?

### ISSUE THREAD

**Issue by ghpille** [pyavitz/rpi-img-builder#39]
After an rpi3-kernel build, is it possible to make further changes to the kernel configuration?

Currently, running "make rpi3-kernel" again will restart with the default configuration, losing all changes one made during the first run.

**Comment by pyavitz** [comment]
After customizing the config, you can continue with your build and then either use the .config file in the source directory or the one left in the /boot directory after the install `as your custom defconfig` in further builds.

https://github.com/pyavitz/rpi-img-builder#user-defconfig

Rename the config to say? ghpille_defconfig and place it in the defconfig directory. When you run `make config` you'll see an option for `user defconfig`. Change the box from to `0` to `1` "this enables the option" and write in the name of the defconfig, which in this case would be: ghpille

**Comment by pyavitz** [comment]
Re-open if needed.
