### ISSUE TITLE
stage1 throws "command not found" error

### ISSUE THREAD

**Issue by alex9434** [pyavitz/rpi-img-builder#4]
Hi, i get the following error message when doing "make image"
```
sudo: ./scripts/rpi4-stage1: command not found
make: *** [Makefile:112: image] Error 1
```
Any idea what command I am missing?

**Comment by pyavitz** [comment]
My bad, something must have got deleted during the last update. 
```
rm -f Makefile
wget -cq https://raw.githubusercontent.com/pyavitz/rpi-img-builder/master/Makefile
```
Please let me know if that fixed the issue. Thanx!

**Comment by alex9434** [comment]
Hi @pyavitz, that solved it. Thank you!
