### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by Bee4Queer** [pyavitz/rpi-img-builder#41]
Could you add support for cygwin so us over on windows can enjoy this super cool thing you made?

**Comment by arakeen** [comment]
If you install WSL2 you can use a Linux instance (Debian or Ubuntu type works best) inside it and it can create the images. You just need to treat the system as a cross compiler system since it is an x86 system and not arm based.

**Comment by Bee4Queer** [comment]
I would but umm... I kind of broke wsl a while ago and I can't figure out how to fix wsl.

**Comment by arakeen** [comment]
The problem is that you need to be emulating the actual os environment (kernel/libraries/binaries) from Linux and Cygwin does not do that. Cygwin is a layer that sits on Win32 to be an Linux API emulation layer. If you use IRC I can help you get WSL fixed however.

**Comment by pyavitz** [comment]
Dual boot on a x86_64 or use an SBC that is running a supported aarch64 distro. I don't have the Windows OS available to me and even if I did, I wouldn't go about making the builder compatible. Someone is more than welcome to do so, if they so wish.

**Comment by Bee4Queer** [comment]
Okay so I'm available at 4:00 CST tomorrow and I will have to get IRC so 4:30 CST tomorrow?

**Comment by Bee4Queer** [comment]
Okay I looked up what IRC is so I mean I will have to get a IRC client

**Comment by arakeen** [comment]
You can use the web based client at https://web.libera.chat. Make sure you read the web pages about registering a nickname or you will not be able to join the support channel as it requires being logged into your account.

**Comment by pyavitz** [comment]
As I don't plan on ever supporting Cygwin, this will be going into the rubbish. If someone feels like doing the work they are more than welcome too.
