### ISSUE TITLE
using make commit kernels in image build

### ISSUE THREAD

**Issue by djsftree** [pyavitz/rpi-img-builder#43]
Hi!

I have sucessfully buit a the 5.15.36-rt41 kernel using 

make commit board=bcm2711
ac27843a367ea253659847aeb491137bf3e9216a

with /patches/userpatches/patch-5.15.36-rt41.patch

The kernel and header deb file appear in /output

How do I install them at the beginning of run_function2 ()  instead of after?  I have some installs within run_function2 () that require the rt kernel and headers.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/10553134/168503331-6e6f1054-4262-4e4c-9e82-92e930aec4de.png">

**Comment by djsftree** [comment]
Ah.  It's ok, the kermel modules get rebuilt.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/10553134/168503789-c8c9f494-fbc4-4f1a-bda3-30a60ebaf389.png">

**Comment by pyavitz** [comment]
Looks like you figured it out? If you really wanted to move it, you could use `function1` to edit the stage2 file before `chroot` and move the kernel install function into `function2`.

```sh
stage2 -> L264: stage2_kernel
```
sed out the function and place `stage2_kernel` inside your `function2` bit. You would just need to make sure all the depends required, get installed before the kernel.

**Comment by djsftree** [comment]
Thanks.  The issue resolved itself as kernel modules are rebuilt when the new kernel is installed.

I spotted this in the logs when cross building userland

`~/userland/build/raspberry/release ~/userland
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at makefiles/cmake/arm-linux.cmake:5 (message):
    *********************************************************                                                                                                
    *   CMAKE_TOOLCHAIN_FILE not defined                    *                                                                                                
    *   This is correct for compiling on the Raspberry Pi   *                                                                                                
    *                                                       *                                                                                                
    *   If you are cross-compiling on some other machine    *                                                                                                
    *   then DELETE the build directory and re-run with:    *                                                                                                
    *   -DCMAKE_TOOLCHAIN_FILE=toolchain_file.cmake         *                                                                                                
    *                                                       *                                                                                                
    *   Toolchain files are in makefiles/cmake/toolchains.  *                                                                                                
    *********************************************************                                                                                                
Call Stack (most recent call first):                                                                                                                         
  CMakeLists.txt:24 (include)             `

**Comment by pyavitz** [comment]
I saw that a whiles back, but haven't found the time to look into it. If you have any ideas, you are more than welcome to do a PR.

**Comment by djsftree** [comment]
Thanks!  Fixing those kind of things is a bit beyond me.

I'm still struggling with setting up the gpg secure keys this repo.  For now --allow-unauthenticated

https://github.com/djsftree/rpi-img-builder/blob/870e0c982185d4dfd79e726e1c5e6cb19b4f6f54/files/userscripts/uscripts#L43

**Comment by pyavitz** [comment]
Example from [website](https://build.opensuse.org/project/show/home:bone11111:branches:science:EtherLab).

```sh
To use this repo please add a file etherlab.list in the directory
/etc/apt/sources.list.d

Using the Release key
1. Get the key
wget http://download.opensuse.org/repositories/home:/bone11111:/branches:/science:/EtherLab/Debian_11/Release.key
2. Add the key
sudo apt-key add Release.key
3. Add the package source url
deb [trusted=yes] http://download.opensuse.org/repositories/home:/bone11111:/branches:/science:/EtherLab/Debian_11/ ./
4. Update package list
sudo apt-get update

Content of the file in case you are not use the secure key:
deb [allow-insecure=yes] http://download.opensuse.org/repositories/home:/bone11111:/branches:/science:/EtherLab/Debian_11/ ./
```

**Comment by djsftree** [comment]
I think that's now deprecated. That key file points to "Release" but this points to "InRelease"

` http://download.opensuse.org/repositories/home:/bone11111:/branches:/science:/EtherLab/Debian_11/ ./ `

In any case, thanks for your great imaging tool.  Just booted!

**Comment by pyavitz** [comment]
> In any case, thanks for your great imaging tool. Just booted!

You are very welcome.
