### ISSUE TITLE
links and donations

### ISSUE THREAD

**Issue by djsftree** [pyavitz/rpi-img-builder#44]
Hi!

Do you have a donation link?

Do you have an updated Discord server? this one goes to nowhere
https://discord.com/channels/898968760457781309/950159122031079524

Just spotted your PayPal.  Is that active still?

**Comment by pyavitz** [comment]
Yea. Thank you very much. That's very kind of you.

**Comment by djsftree** [comment]
No problem! :-)

**Comment by pyavitz** [comment]
The link works for me, but I didn't set it up. Here is an invite: https://discord.gg/qMwwHEwS
