### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by CountKeepo** [pyavitz/rpi-img-builder#46]
Hey!

Doesn't relate to the code but the Discord link in the MD file is not correct so I can't join in and chat.

It needs to be an invite link, not a link to a specific channel.

**Comment by pyavitz** [comment]
These only last 7 days, so just leave the issue open.

https://discord.gg/qMwwHEwS

**Comment by CountKeepo** [comment]
Fixed with a new invite link that doesn't expire it seems!
