### ISSUE TITLE
Unable to see /dev/ttyAMA0

### ISSUE THREAD

**Issue by RosiersRobin** [pyavitz/rpi-img-builder#65]
Hi,

I compiled the image and it worked out of the box, no biggy, however it seems I cannot see the /dev/ttyAMA0 device. It's a RPI hat plugged in (qibixx). Anyone an idea? I normally can access it via minicom and run some serial command. Now, I cannot. /dev/TTY0 doesn't do much either.

Any ideas here?

**Comment by RosiersRobin** [comment]
Update: when I check my dmesg, I see this:

[    4.626569] uart-pl011 fe201000.serial: there is not valid maps for state default
[    4.627434] uart-pl011 fe201000.serial: cts_event_workaround enabled
[    4.627600] fe201000.serial: ttyAMA1 at MMIO 0xfe201000 (irq = 36, base_baud = 0) is a PL011 rev2
[    4.627846] serial serial0: tty port ttyAMA1 registered
[    4.637305] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    4.637769] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    4.639291] mmc-bcm2835 fe300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    4.639313] mmc-bcm2835 fe300000.mmcnr: DMA channel allocated
[    4.666670] of_cfs_init
[    4.666839] of_cfs_init: OK
[    4.703972] mmc0: SDHCI controller on fe340000.mmc [fe340000.mmc] using ADMA

**Comment by pyavitz** [comment]
Did you get this resolved?

**Comment by RosiersRobin** [comment]
I got it resolved by disabling the bluetooth in the configs;

![image](https://github.com/pyavitz/rpi-img-builder/assets/5263188/04457912-bf80-4fc9-9e9f-3b61b68681cf)

However, the serial port is acting up weird. I tried the same setup with the same hardware, but with Ubuntu server 22.04 and it didn't act up.

this is what hapens:
![cmd_QZwURwjTrh](https://github.com/pyavitz/rpi-img-builder/assets/5263188/b629e147-4624-4d67-8630-68d6b3d3a817)

**Comment by pyavitz** [comment]
Hmm. Nothing to me is standing out, other than Ubuntu is running `Linux 5.15.y`. Sorry you had issues.

**Comment by RosiersRobin** [comment]
i'm going to try and compile with the lower kernel version and see if the issues still persist. If they don't, then there must be something with the kernel going on I think..?

**Comment by RosiersRobin** [comment]
Tested with an older kernel, seems like it's still the same "laggy" serial. I'll try different hardware.

**Comment by RosiersRobin** [comment]
Exactly the same with different hardware. On the RPI3 modebl B+ it works like a charm (with raspbian) but on the 4 it does not.

**Comment by pyavitz** [comment]
I have no clue what the solution would be. It could be something simple, but without the HW myself I can't debug.

**Comment by RosiersRobin** [comment]
Compiling using debian instead of ubuntu as distro resolved the issue.
