### ISSUE TITLE
Multi board image

### ISSUE THREAD

**Issue by jayofelony** [pyavitz/rpi-img-builder#66]
Would it be possible to build an image for multiple boards at the same time?
02w, 3, 4 and 5 all at once arm64 only with kernel 6.6.y.

Like an all in one image as with the current raspios lite 64 bit.

**Comment by pyavitz** [comment]
Technically the RPI4 `aarch64` `bcm2711` img should work with those units. Basically one img to rule them all.

**Comment by jayofelony** [comment]
Can you make it add the bcm2712-rpi-5.dtb to it as well when you build an image for pi 4? The bcm2710 is also there when you build the 2711 (pi4/400).

**Comment by pyavitz** [comment]
> bcm2712-rpi-5.dtb

Is it not there? It should be.

**Comment by jayofelony** [comment]
When i build a pi 4 image there is no pi5 dtb there, it boots fine on 02 and 4, but not on the 5

Kernel 6.2.y

**Comment by pyavitz** [comment]
That's because ur using 6.2.y and the DTS wasn't introduced. That kernel is EOL and the PI5 DTS wasn't added until after the fact.

It was added to 6.1.y because they are still using that kernel as an LTS. Eventually they will move on to 6.6 LTS and drop support for 6.1.y.
